### ISSUE TITLE
.htaccess example RewriteRule has unnecessary leading slash

### ISSUE THREAD

**Issue by jgusta** [stein189/SimpleRouting#16]
This tripped me up a bit. In your sample htaccess ruleset from README you suggest the following to remove trailing slashes:
```
# Redirect Trailing Slashes...
RewriteRule ^(.*)/$ /$1 [L,R=301]
```
However, the leading slash on the substitution portion is unnecessary and causes all replacements to be absolute paths. This gives undesired results if you are running the router from a base directory other than the URL root. This should be sufficient:
```
# Redirect Trailing Slashes...
RewriteRule ^(.*)/$ $1 [L,R=301]
```
And it works with a non-root URI base path as well as using a RewriteBase directive.

**Comment by stein189** [comment]
Thank you for your feedback, I will take a look at it today.

**Comment by stein189** [comment]
I have been looking for the best possible solutions for both situations and I found the following snippet:

```
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} (.+)/$
RewriteRule ^ %1 [R=301,L]
```

Could you tell me if this snippet also solves your problem?
