### ISSUE TITLE
action_type vs actionType in URL

### ISSUE THREAD

**Issue by riso348** [stein189/SimpleRouting#26]
Hi, 
look at this problem i have (v2.0.1):

`$router->add('/admin_crm/{w:controller}/{a:action_type}/ajax/{a:action}', 'GET', function ($controller, $action_type, $action) { ... }`
 arguments in url, controller, action_type, action.

After i dump this route in RouteResolver i got this:

```
Szenis\Routing\Route Object
(
    [method:Szenis\Routing\Route:private] => Array
        (
            [0] => GET
        )

    [url:Szenis\Routing\Route:private] => admin_crm\/([0-9a-zA-Z-_]++)\/([a-zA-Z]++)\/ajax\/([a-zA-Z]++)
    [action:Szenis\Routing\Route:private] => Closure Object
        (
            [parameter] => Array
                (
                    [$controller] => 
                    [$action_type] => 
                    [$action] => 
                )

        )

    [arguments:Szenis\Routing\Route:private] => Array
        (
            [0] => controller
            [1] => action
        )

)
```
with no **action_type** argument in Arguments but if i change argument name from
**action_type** TO **actionType**, it works. There may be some problem with underscore variable.

**Comment by riso348** [comment]
I check the RouteFactory and maybe there is missing _ (underscore)

`preg_match_all('~{(n:|a:|an:|w:|\*:|\?:)?([a-zA-Z0-9]+)}~', $url, $matches);`
`preg_match_all('~{(n:|a:|an:|w:|\*:|\?:)?([a-zA-Z0-9_]+)}~', $url, $matches); `  - works good

**Comment by stein189** [comment]
@riso348 

That was the probleem indeed, I updated the code. It should work now in version 2.0.2

**Comment by riso348** [comment]
yes now it works, thank you :-)
