### ISSUE TITLE
Page auto-change is not functioning properly

### ISSUE THREAD

**Issue by you0me0** [stein189/SimpleRouting#30]
Hello.

How do I report that if I connect to the sub-folder in the root folder, I don't have to print the error ' Automatically change pages ' and print them with other errors?

```
$response = $router->resolve($_SERVER['REQUEST_URI'], $_SERVER['REQUEST_METHOD']);
switch ($response['code']) {
    case \Szenis\Routing\Route::STATUS_MOVED:
    $temp = new Controller\templates();
    $temp->templates('error/403');
```

But it didn't work.

Using papago, the English language is not smooth. I'm sorry.

**Comment by stein189** [comment]
The router doesn't have the constant STATUS_MOVED, I am not sure what you try to accomplish.
Please ask your questions on stackoverflow instead of github.
