### ISSUE TITLE
RewriteBase

### ISSUE THREAD

**Issue by mrl22** [stein189/SimpleRouting#32]
First, thank you for a great class.

Do you happen to know I get this to work from within a subdirectory? Currently, I am having to prepend my directory name to every route.

For example:

$router->add( '/subdir/login', 'GET', function () {
	return 'login page here';
} );

Thanks again.

**Comment by stein189** [comment]
@mrl22 

If I understand your question correctly then you can solve the problem by moving the .htaccess to the "subdir" folder and change your apache (or nginx) document root to the "subdir" folder aswell.

**Comment by mrl22** [comment]
Thank you for your message @stein189 .

To give you a little background, I am writing an open source crm. The project needs to be able to run inside and outside of a subfolder without the user needing to change any PHP code and the ability to run on shared hosting accounts without needing to modify apache/nginx config files.

So at the moment I have the platform running at https://devfwd.com/mailcrm/ I have a .htaccess inside the mailcrm folder:

RewriteEngine On
RewriteRule ^(.*)/$ /mailcrm/$1 [L,R=301]
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]


But I still need to add mailcrm to the PHP code:

$router->add( '/mailcrm/login', 'GET', function () {
return 'login page here';
} );

https://devfwd.com/mailcrm/login

I would have no problem if the user had to make a small change to the htaccess file if the prject was in a subfolder.

Thanks again,

Richard

**Comment by stein189** [comment]
Hi @mrl22 ,

I think it's possible but I dont know how to accomplish that. 
Maybe it's a good idea to ask your question on https://stackoverflow.com
